import { expect,test } from "@playwright/test";
test("grid grows and shrinks smoothly, preserves camera and themes, and respects reduced motion",async({page},info)=>{
 await page.goto("/");await page.getByRole("button",{name:"Новый проект",exact:true}).click();await page.getByRole("button",{name:"Создать проект",exact:true}).click();const canvas=page.locator("canvas");await expect.poll(async()=>JSON.parse(await canvas.getAttribute("data-grid")??"{}").distance).toBe(550);
 // Replace only geometry in an isolated viewer to avoid changing the workspace or fitting its camera.
 await page.evaluate(async()=>{const React=await import("/node_modules/.vite/deps/react.js"),DOM=await import("/node_modules/.vite/deps/react-dom_client.js"),F=await import("/node_modules/.vite/deps/@react-three_fiber.js"),THREE=await import("/node_modules/.vite/deps/three.js"),{AdaptiveGrid}=await import("/src/features/viewer/grid/AdaptiveGrid.tsx");const host=document.body.appendChild(document.createElement("div"));host.style.cssText="position:fixed;inset:20px;z-index:1000;background:#202326";const root=DOM.default.createRoot(host);let light=false;let object=new THREE.Group();object.add(new THREE.Mesh(new THREE.BoxGeometry(40,20,10)));const render=()=>root.render(React.default.createElement(F.Canvas,{camera:{position:[180,140,180],fov:38}},React.default.createElement(AdaptiveGrid,{object,light})));(window as any).setGrid=(size:number,x=0)=>{object=new THREE.Group();const mesh=new THREE.Mesh(new THREE.BoxGeometry(size,size/2,size/3));mesh.position.x=x;object.add(mesh);render();};(window as any).gridTheme=()=>{light=!light;render();};render();});
 const gridCanvas=page.locator("canvas").last();await expect.poll(async()=>JSON.parse(await gridCanvas.getAttribute("data-grid")??"{}").distance).toBe(550);
 await page.evaluate(()=>(window as any).setGrid(5000));const samples=await gridCanvas.evaluate(async element=>{const samples=[];for(let n=0;n<45;n++){await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));samples.push(JSON.parse((element as HTMLCanvasElement).dataset.grid!).distance);}return samples;});expect(samples.at(-1)).toBeGreaterThan(5000);samples.forEach((sample:number,i:number)=>{if(i)expect(sample).toBeGreaterThanOrEqual(samples[i-1]-1e-6);});
 const grown=samples.at(-1)!;await page.evaluate(()=>(window as any).gridTheme());expect(JSON.parse(await gridCanvas.getAttribute("data-grid")??"{}").distance).toBeCloseTo(grown,5);await gridCanvas.screenshot({path:info.outputPath("large-light.png")});
 await page.evaluate(()=>(window as any).setGrid(40));await expect.poll(async()=>JSON.parse(await gridCanvas.getAttribute("data-grid")??"{}").distance).toBe(550);
 await page.emulateMedia({reducedMotion:"reduce"});await page.evaluate(()=>(window as any).setGrid(40,10000));await expect.poll(async()=>JSON.parse(await gridCanvas.getAttribute("data-grid")??"{}").distance).toBeGreaterThan(25000);expect(JSON.parse(await gridCanvas.getAttribute("data-grid")??"{}").moving).toBe(false);
});
