import { expect,test,type Page } from "@playwright/test";
import { circularMeasurementFixture } from "./circularMeasurementFixture";
const fixture=circularMeasurementFixture();
const labels={ru:{measure:"Измерить выделение",radius:"Радиус выбранного ребра",diameter:"Диаметр выбранного ребра",plane:"Выбранная плоская грань",area:"Площадь выбранной грани",edge:"Выбрать CAD-ребро",face:"Выбрать CAD-грань"},en:{measure:"Measure selection",radius:"Selected edge radius",diameter:"Selected edge diameter",plane:"Selected planar face",area:"Selected face area",edge:"Select CAD edge",face:"Select CAD face"}};
async function kind(page:Page,label:string){await page.locator(".reference-measurement").getByRole("combobox").click();await page.getByRole("option",{name:label,exact:true}).click();}
async function choose(page:Page,type:"edges"|"faces",role:string){
 await expect.poll(()=>page.evaluate(({type,role})=>(window as any).__applyHarness.candidates()?.[type].find((item:any)=>item.reference?.role===role)??null,{type,role})).not.toBeNull();
 const target=await page.evaluate(({type,role})=>(window as any).__applyHarness.candidates()[type].find((item:any)=>item.reference?.role===role),{type,role});await page.mouse.click(target.x,target.y);
 await expect.poll(()=>page.evaluate(type=>type==="edges"?(window as any).__applyHarness.selectedEdge()?.topologyRef:(window as any).__applyHarness.selectedFace()?.topologyRef,type)).toEqual(target.reference);
}
for(const locale of ["ru","en"] as const)test(`actual App circular ${locale}: real picks, native radius/diameter, units, cap and side, themes and motion`,async({page},info)=>{
 test.skip(!fixture,"Requires the fresh circle-enabled local worker");const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
 await page.route(/\/src\/main\.tsx(?:\?.*)?$/,route=>route.fulfill({contentType:"application/javascript",body:"export {};"}));await page.addInitScript(locale=>localStorage.setItem("forma.locale",locale),locale);await page.goto("/");await page.evaluate(async fixture=>{const{mountCircularMeasurementHarness}=await import("/e2e/circularMeasurementHarness.tsx");await mountCircularMeasurementHarness(fixture);},fixture!);
 await expect(page.locator(".viewer-area")).toHaveAttribute("data-scene-phase","ready");const panel=page.locator(".reference-measurement").first();await panel.locator("summary").first().click();const measure=panel.getByRole("button",{name:labels[locale].measure,exact:true});
 await page.getByRole("button",{name:labels[locale].edge,exact:true}).click();await choose(page,"edges","cylinder-edge:top");
 await kind(page,labels[locale].radius);await measure.click();await expect(panel.locator("dd").first()).toHaveText(locale==="ru"?"25,4 мм":"25.4 mm");
 await expect(panel).not.toContainText(locale==="ru"?"прямое ребро":"straight");
 await kind(page,labels[locale].diameter);await measure.click();await expect(panel.locator("dd").first()).toHaveText(locale==="ru"?"50,8 мм":"50.8 mm");
 for(const units of ["inch","cm","mm"]){await page.evaluate(units=>(window as any).__applyHarness.units(units),units);const value=units==="inch"?2:units==="cm"?5.08:50.8,symbol=units==="inch"?(locale==="ru"?"дюйм":"in"):units==="cm"?(locale==="ru"?"см":"cm"):locale==="ru"?"мм":"mm";await expect(panel.locator("dd").first()).toHaveText(`${new Intl.NumberFormat(locale==="ru"?"ru-RU":"en-US",{maximumFractionDigits:3}).format(value)} ${symbol}`);}
 for(const theme of ["light","dark"]){await page.evaluate(theme=>(window as any).__applyHarness.theme(theme),theme);for(let repeat=0;repeat<2;repeat++){const count=Number(await panel.locator(".editor-disclosure-body").first().getAttribute("data-animation-count"));await panel.locator("summary").first().click();await panel.locator("summary").first().click();await expect.poll(async()=>Number(await panel.locator(".editor-disclosure-body").first().getAttribute("data-animation-count"))).toBeGreaterThan(count);}expect(await measure.evaluate(element=>element.getBoundingClientRect().height)).toBe(32);await page.screenshot({path:info.outputPath(`circular-${locale}-${theme}.png`)});}
 await page.getByRole("button",{name:labels[locale].face,exact:true}).click();await choose(page,"faces","cylinder-face:top");await kind(page,labels[locale].plane);await measure.click();await expect(panel.locator("dd").nth(2)).toHaveText("0 · 0 · 1");
 await choose(page,"faces","cylinder-face:side");await panel.getByRole("combobox").click();await expect(page.getByRole("option",{name:labels[locale].plane,exact:true})).toHaveCount(0);await page.getByRole("option",{name:labels[locale].area,exact:true}).click();await measure.click();await expect(panel.locator("dd").first()).toHaveText(`${new Intl.NumberFormat(locale==="ru"?"ru-RU":"en-US",{maximumFractionDigits:3}).format(2*Math.PI*25.4*10)} ${locale==="ru"?"мм":"mm"}²`);
 expect(await page.evaluate(()=>(window as any).__applyHarness.candidates().catalog.filter((item:any)=>item?.kind==="edge").length)).toBe(2);expect(await page.evaluate(()=>(window as any).__applyHarness.candidates().catalog.some((item:any)=>item===null))).toBe(true);
 await page.evaluate(()=>(window as any).__applyHarness.seam());await panel.getByRole("combobox").click();await expect(page.getByRole("option",{name:labels[locale].radius,exact:true})).toHaveCount(0);await expect(page.getByRole("option",{name:labels[locale].diameter,exact:true})).toHaveCount(0);await page.keyboard.press("Escape");
 expect(await page.evaluate(()=>(window as any).__applyHarness.calls.filter((call:any)=>call.command==="apply_program"||call.command==="request_permission"))).toEqual([]);expect(errors).toEqual([]);
});
