import { expect,test } from "@playwright/test";
for(const locale of ["ru","en"] as const)test(`editor sections animate real heights and align controls in ${locale}`,async({page},info)=>{
 test.setTimeout(150000);
 await page.addInitScript(locale=>localStorage.setItem("forma.locale",locale),locale);await page.goto("/");
 await page.evaluate(async()=>{const React=await import("/node_modules/.vite/deps/react.js"),DOM=await import("/node_modules/.vite/deps/react-dom_client.js"),{ProgramDialog}=await import("/src/app/dialogs/ProgramDialog.tsx"),{createLinkedProfiles}=await import("/src/lib/templates/linkedProfiles.ts");DOM.default.createRoot(document.body.appendChild(document.createElement("div"))).render(React.default.createElement(ProgramDialog,{open:true,close:()=>{},source:createLinkedProfiles(),disabled:false,nativeCadAvailable:true,nativeCadChecked:true,onApply:()=>{}}));});
 const sample=async(selector:string,open:boolean)=>page.locator(selector).first().evaluate(async(details,open)=>{const body=details.querySelector(":scope > .editor-disclosure-body") as HTMLElement;(details.querySelector("summary") as HTMLElement).click();const heights=[];for(let i=0;i<24;i++){await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));heights.push(body.getBoundingClientRect().height);}return {heights,full:body.scrollHeight,expanded:details.getAttribute("data-expanded"),nativeOpen:details.hasAttribute("open"),open};},open);
 for(const selector of [".cad-parameter-editor",".edge-fillet-editor",".sketch-editor",".model-editor-source"]){const section=page.locator(selector).first();if(await section.getAttribute("data-expanded")==="true"){await section.locator(":scope > summary").click();await expect(section).not.toHaveAttribute("open","");}
  for(let pass=0;pass<2;pass++){const opened=await sample(selector,true);expect(opened.heights.some(h=>h>1&&h<opened.full-1)).toBe(true);expect(opened.expanded).toBe("true");const closed=await sample(selector,false);expect(closed.heights.some(h=>h>1&&h<closed.full-1)).toBe(true);expect(closed.nativeOpen).toBe(false);}
 }
 const sketch=page.locator(".sketch-editor").first();await sketch.locator("summary").click();await expect(sketch).toHaveAttribute("data-expanded","true");await page.waitForTimeout(300);
 const reversed=await sketch.evaluate(async details=>{const body=details.querySelector(":scope>.editor-disclosure-body") as HTMLElement,summary=details.querySelector("summary") as HTMLElement;summary.click();await new Promise(resolve=>setTimeout(resolve,70));const before=body.getBoundingClientRect().height;summary.click();await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const after=body.getBoundingClientRect().height;await new Promise(resolve=>setTimeout(resolve,350));return {before,after,full:body.scrollHeight,final:body.getBoundingClientRect().height,expanded:details.getAttribute("data-expanded")};});expect(reversed.expanded).toBe("true");expect(Math.abs(reversed.after-reversed.before)).toBeLessThan(reversed.full*.15);expect(Math.abs(reversed.final-reversed.full)).toBeLessThan(2);
 const name=await page.locator(".typed-feature-name").first().boundingBox(),label=await sketch.locator("summary>span").last().boundingBox();expect(Math.abs(name!.x-label!.x)).toBeLessThan(2);
 for(const theme of ["dark","light"]){await page.evaluate(async theme=>{const {applyTheme}=await import("/src/lib/theme.ts");applyTheme(theme);},theme);
  for(const selector of [".sketch-editor-construction-add",".sketch-editor-coincident",".sketch-link-add"]){const row=sketch.locator(selector);await row.scrollIntoViewIfNeeded();const button=await row.locator(":scope > button").boundingBox();const fields=await row.locator("label [role=combobox]").all();for(const field of fields){const box=await field.boundingBox();expect(box!.height).toBe(32);expect(button!.height).toBe(32);expect(Math.abs(box!.y+box!.height-button!.y-button!.height)).toBeLessThan(2);expect(Math.abs(box!.y-button!.y)).toBeLessThan(2);}await row.screenshot({path:info.outputPath(`${selector.slice(1)}-${locale}-${theme}.png`)});}
 }
 await page.emulateMedia({reducedMotion:"reduce"});await sketch.locator("summary").focus();await page.keyboard.press("Enter");await expect(sketch).not.toHaveAttribute("open","");await page.keyboard.press("Enter");await expect(sketch).toHaveAttribute("open","");expect(await sketch.locator(":scope>.editor-disclosure-body").evaluate(el=>el.getAnimations().length)).toBe(0);
 await page.setViewportSize({width:700,height:850});await sketch.locator(".sketch-link-add").scrollIntoViewIfNeeded();await sketch.locator(".sketch-links").screenshot({path:info.outputPath(`links-${locale}-narrow.png`)});
});
