import { expect,test,type Page } from "@playwright/test";
import { faceSectionFixture } from "./faceSectionFixture";
const fixture=faceSectionFixture();
const words={ru:{face:"Выбрать CAD-грань",section:"Сечение модели",source:"Источник сечения",selected:"Выбранная CAD-грань",manual:"Числовая или произвольная плоскость",calculate:"Рассчитать сечение",auto:"Обновлять сечение по грани автоматически",offset:"Смещение от выбранной грани",hide:"Скрыть",whole:"включая скрытые тела",clip:"Отсекать модель плоскостью сечения"},en:{face:"Select CAD face",section:"Section view",source:"Section source",selected:"Selected CAD face",manual:"Numeric or free plane",calculate:"Calculate section",auto:"Update face section automatically",offset:"Offset from selected face",hide:"Hide",whole:"including hidden bodies",clip:"Clip model with section plane"}};
async function mount(page:Page,locale:"ru"|"en"){
 await page.route(/\/src\/main\.tsx(?:\?.*)?$/,route=>route.fulfill({contentType:"application/javascript",body:"export {};"}));await page.addInitScript(locale=>localStorage.setItem("forma.locale",locale),locale);await page.goto("/");await page.evaluate(async fixture=>{const{mountFaceSectionHarness}=await import("/e2e/faceSectionHarness.tsx");await mountFaceSectionHarness(fixture);},fixture!);
 await expect(page.locator(".viewer-area")).toHaveAttribute("data-scene-phase","ready");await page.getByRole("button",{name:words[locale].face,exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.candidates()?.faces.find((item:any)=>item.reference?.role==="box-face:zmax")??null)).not.toBeNull();const target=await page.evaluate(()=>(window as any).__applyHarness.candidates().faces.find((item:any)=>item.reference?.role==="box-face:zmax"));await page.mouse.click(target.x,target.y);await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.selectedFace()?.topologyRef)).toEqual(target.reference);
 await page.getByRole("button",{name:words[locale].section,exact:true}).click();const controls=page.locator(".section-controls");await controls.getByRole("combobox",{name:words[locale].source,exact:true}).click();await page.getByRole("option",{name:words[locale].selected,exact:true}).click();return controls;
}
for(const locale of ["ru","en"] as const){
 test(`actual App face section ${locale}: real face pick, verified plane, whole hidden STEP, units, explicit calculation and motion`,async({page},info)=>{
  test.skip(!fixture,"Requires the current face-section worker");const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));const controls=await mount(page,locale),calculate=controls.getByRole("button",{name:words[locale].calculate,exact:true}),offset=controls.getByRole("spinbutton",{name:new RegExp(words[locale].offset)});
  await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionInspection().clipping)).toBe(1);await controls.getByRole("checkbox",{name:words[locale].auto,exact:true}).click();await offset.fill("-2");await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionInspection().clipping)).toBe(0);await calculate.click();
  const expected=new Intl.NumberFormat(locale==="ru"?"ru-RU":"en-US",{maximumFractionDigits:3}).format(120+16*Math.PI);await expect(controls).toContainText(`${expected} ${locale==="ru"?"мм":"mm"}`);await expect(controls).toContainText(words[locale].whole);
  const initial=await page.evaluate(()=>(window as any).__applyHarness.sectionInspection());expect(initial.clipping).toBe(1);initial.plane.normal.forEach((value:number,index:number)=>expect(value).toBeCloseTo([0,1,0][index],8));expect(initial.plane.constant).toBeCloseTo(-8,6);
  const hide=page.getByRole("button",{name:new RegExp(`^${words[locale].hide} .*Cylinder`)});await hide.click();await expect(controls).toContainText(`${expected} ${locale==="ru"?"мм":"mm"}`);await calculate.click();await expect(calculate).toBeEnabled();
  for(const units of ["cm","inch","mm"]){await page.evaluate(units=>(window as any).__applyHarness.units(units),units);expect(Number(await offset.inputValue())).toBeCloseTo(units==="cm"?-.2:units==="inch"?-2/25.4:-2,8);}
  for(const theme of ["light","dark"]){await page.evaluate(theme=>(window as any).__applyHarness.theme(theme),theme);for(let repeat=0;repeat<2;repeat++){await controls.locator("summary").click();await expect(controls).toHaveCount(0);await page.getByRole("button",{name:words[locale].section,exact:true}).click();await expect(controls).toBeVisible();expect(await controls.evaluate(element=>getComputedStyle(element).animationDuration)).toBe("0.2s");expect(await controls.locator("summary svg").last().evaluate(element=>getComputedStyle(element).transitionDuration)).toBe("0.26s");}expect(await calculate.evaluate(element=>element.getBoundingClientRect().height)).toBe(32);await expect.poll(()=>controls.evaluate(element=>({opacity:Number(getComputedStyle(element).opacity),running:element.getAnimations({subtree:true}).filter(animation=>animation.playState==="running").length}))).toEqual({opacity:1,running:0});await page.screenshot({path:info.outputPath(`face-section-${locale}-${theme}.png`)});}
  expect((await page.evaluate(()=>(window as any).__applyHarness.sectionInspection())).camera).toEqual(initial.camera);
  await offset.fill("6");await calculate.click();await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionInspection().plane?.constant)).toBeCloseTo(-16,6);await expect(controls).toContainText(`0 ${locale==="ru"?"мм":"mm"}`);
  await controls.getByRole("combobox",{name:words[locale].source,exact:true}).click();await page.getByRole("option",{name:words[locale].manual,exact:true}).click();await expect(controls.getByRole("combobox",{name:locale==="ru"?"Плоскость сечения":"Section plane",exact:true})).toBeVisible();await controls.getByRole("checkbox",{name:words[locale].clip,exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionInspection().clipping)).toBe(0);
  expect(await page.evaluate(()=>(window as any).__applyHarness.calls.filter((call:any)=>call.command==="apply_program"||call.command==="request_permission"))).toEqual([]);expect(errors).toEqual([]);
 });
 test(`actual App face section ${locale}: source seal change hides clipping before a delayed result`,async({page})=>{
  test.skip(!fixture,"Requires the current face-section worker");const controls=await mount(page,locale),calculate=controls.getByRole("button",{name:words[locale].calculate,exact:true}),offset=controls.getByRole("spinbutton",{name:new RegExp(words[locale].offset)});
  await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionInspection().clipping)).toBe(1);await controls.getByRole("checkbox",{name:words[locale].auto,exact:true}).click();await page.evaluate(()=>(window as any).__applyHarness.delaySection(true));await offset.fill("-2");await calculate.click();await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionPending())).toBe(true);
  await page.evaluate(()=>(window as any).__applyHarness.sourceSeal("b".repeat(64)));await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.sectionInspection().clipping)).toBe(0);await page.evaluate(()=>(window as any).__applyHarness.releaseSection());await expect(calculate).toBeEnabled();expect(await page.evaluate(()=>(window as any).__applyHarness.sectionInspection().clipping)).toBe(0);
 });
}
