import { expect,test,type Page } from "@playwright/test";
import { pairMeasurementFixture } from "./pairMeasurementFixture";
const fixture=pairMeasurementFixture();
test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus){const probe=await page.evaluate(()=>({candidates:(window as any).__applyHarness?.candidates?.(),selectedEdge:(window as any).__applyHarness?.selectedEdge?.(),selectedFace:(window as any).__applyHarness?.selectedFace?.()})).catch(error=>({error:String(error)}));await info.attach("actual-pair-picking-probe",{body:JSON.stringify(probe),contentType:"application/json"});}});
const words={ru:{title:"Точные измерения между элементами",edge:"Выбрать CAD-ребро",face:"Выбрать CAD-грань",first:"Сохранить первый выбор",second:"Сохранить второй выбор",measure:"Измерить выбранную пару",normal:"Угол внешних нормалей граней (0–180°)",acute:"Острый угол прямых рёбер (0–90°)"},en:{title:"Exact pair measurements",edge:"Select CAD edge",face:"Select CAD face",first:"Capture first selection",second:"Capture second selection",measure:"Measure captured pair",normal:"Outward face-normal angle (0–180°)",acute:"Acute straight-edge angle (0–90°)"}};
async function mount(page:Page,locale:"ru"|"en"){
 await page.route(/\/src\/main\.tsx(?:\?.*)?$/,route=>route.fulfill({contentType:"application/javascript",body:"export {};"}));await page.addInitScript(locale=>localStorage.setItem("forma.locale",locale),locale);await page.goto("/");await page.evaluate(async fixture=>{const{mountPairMeasurementHarness}=await import("/e2e/pairMeasurementHarness.tsx");await mountPairMeasurementHarness(fixture);},fixture!);
 await expect(page.locator(".viewer-area")).toHaveAttribute("data-scene-phase","ready");const panel=page.locator(".pair-measurement");await panel.locator("summary").click();return panel;
}
async function pick(page:Page,type:"edges"|"faces",role:string){
 await expect.poll(()=>page.evaluate(({type,role})=>(window as any).__applyHarness.candidates()?.[type].find((item:any)=>item.reference?.role===role)??null,{type,role})).not.toBeNull();
 const target=await page.evaluate(({type,role})=>(window as any).__applyHarness.candidates()[type].find((item:any)=>item.reference?.role===role),{type,role});await page.mouse.click(target.x,target.y);
 await expect.poll(()=>page.evaluate(type=>type==="edges"?(window as any).__applyHarness.selectedEdge()?.topologyRef:(window as any).__applyHarness.selectedFace()?.topologyRef,type)).toEqual(target.reference);
}
async function availablePair(page:Page,kind:string){
 await expect.poll(()=>page.evaluate(kind=>{const harness=(window as any).__applyHarness,candidates=harness.candidates();return harness.pairQueries.find((query:any)=>query.kind===kind&&[query.first,query.second].every(ref=>candidates[ref.kind==="edge"?"edges":"faces"].some((item:any)=>item.reference?.role===ref.role)))??null;},kind)).not.toBeNull();
 return page.evaluate(kind=>{const harness=(window as any).__applyHarness,candidates=harness.candidates();return harness.pairQueries.find((query:any)=>query.kind===kind&&[query.first,query.second].every(ref=>candidates[ref.kind==="edge"?"edges":"faces"].some((item:any)=>item.reference?.role===ref.role)));},kind);
}
for(const locale of ["ru","en"] as const){
 test(`actual App pair ${locale}: genuine viewport captures, exact distance/angles, units and settled motion/themes`,async({page},info)=>{
  test.skip(!fixture,"Requires verified pair-enabled native worker");const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));const panel=await mount(page,locale),measure=panel.getByRole("button",{name:words[locale].measure,exact:true});await expect(measure).toBeDisabled();
  await page.getByRole("button",{name:words[locale].edge,exact:true}).click();const pair=await availablePair(page,"minimumDistance");
  await pick(page,"edges",pair.first.role);await panel.getByRole("button",{name:words[locale].first,exact:true}).click();await pick(page,"edges",pair.second.role);await panel.getByRole("button",{name:words[locale].second,exact:true}).click();await measure.click();await expect(panel.locator("dd").first()).toHaveText(locale==="ru"?"10 мм":"10 mm");
  for(const units of ["cm","inch","mm"]){await page.evaluate(units=>(window as any).__applyHarness.units(units),units);const number=new Intl.NumberFormat(locale==="ru"?"ru-RU":"en-US",{maximumFractionDigits:3}).format(units==="cm"?1:units==="inch"?10/25.4:10);await expect(panel.locator("dd").first()).toHaveText(`${number} ${units==="cm"?(locale==="ru"?"см":"cm"):units==="inch"?(locale==="ru"?"дюйм":"in"):locale==="ru"?"мм":"mm"}`);}
  await panel.getByRole("combobox").click();await page.getByRole("option",{name:words[locale].acute,exact:true}).click();await measure.click();await expect(panel.locator("dd").first()).toHaveText("0°");
  await page.getByRole("button",{name:words[locale].face,exact:true}).click();const faces=await availablePair(page,"faceNormalAngle");await pick(page,"faces",faces.first.role);await panel.getByRole("button",{name:words[locale].first,exact:true}).click();await pick(page,"faces",faces.second.role);await panel.getByRole("button",{name:words[locale].second,exact:true}).click();await panel.getByRole("combobox").click();await page.getByRole("option",{name:words[locale].normal,exact:true}).click();await measure.click();await expect(panel.locator("dd").first()).toHaveText("90°");
  for(const theme of ["light","dark"]){await page.evaluate(theme=>(window as any).__applyHarness.theme(theme),theme);for(let repeat=0;repeat<2;repeat++){const count=Number(await panel.locator(".editor-disclosure-body").getAttribute("data-animation-count"));await panel.locator("summary").click();await panel.locator("summary").click();await expect.poll(async()=>Number(await panel.locator(".editor-disclosure-body").getAttribute("data-animation-count"))).toBeGreaterThan(count);}await expect.poll(()=>panel.evaluate(element=>element.getAnimations({subtree:true}).filter(animation=>animation.playState==="running").length)).toBe(0);expect(await measure.evaluate(element=>element.getBoundingClientRect().height)).toBe(32);expect(await panel.evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);await measure.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`pair-${locale}-${theme}.png`)});}
  expect(await page.evaluate(()=>(window as any).__applyHarness.calls.filter((call:any)=>call.command==="apply_program"||call.command==="request_permission"))).toEqual([]);expect(errors).toEqual([]);
 });
 test(`actual App pair ${locale}: source identity invalidates captured slots and late answers`,async({page})=>{
  test.skip(!fixture,"Requires verified pair-enabled native worker");const panel=await mount(page,locale);await page.getByRole("button",{name:words[locale].edge,exact:true}).click();const pair=await availablePair(page,"minimumDistance");await pick(page,"edges",pair.first.role);await panel.getByRole("button",{name:words[locale].first,exact:true}).click();await pick(page,"edges",pair.second.role);await panel.getByRole("button",{name:words[locale].second,exact:true}).click();await page.evaluate(()=>(window as any).__applyHarness.delayPair(true));await panel.getByRole("button",{name:words[locale].measure,exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__applyHarness.pairPending())).toBe(true);
  await page.evaluate(()=>(window as any).__applyHarness.sourceSeal("b".repeat(64)));await expect(panel.getByRole("button",{name:words[locale].measure,exact:true})).toBeDisabled();await expect(panel.locator("dd")).toHaveCount(0);await page.evaluate(()=>(window as any).__applyHarness.releasePair());await expect(panel.locator("dd")).toHaveCount(0);
 });
}


